export type Category = "Classical" | "Pop" | "Entrance" | "Recessional";

export type Song = {
  id: string;
  title: string;
  composer: string;
  category: Category;
};

const classical: [string, string][] = [
  ["Adagio from Suite for Organ", "Tomaso Albinoni"],
  ["Adagio from Moonlight Sonata", "Ludwig van Beethoven"],
  ["Air on the G String", "J. S. Bach"],
  ["Air from Water Music", "George Frideric Handel"],
  ["Allegro", "Joseph-Hector Fiocco"],
  ["Allegro from Eine kleine Nachtmusik", "W. A. Mozart"],
  ["Allelujah", "W. A. Mozart"],
  ["Amoroso", "Thomas Arne"],
  ["Andante Festivo", "Jean Sibelius"],
  ["Andante from Berenice", "George Frideric Handel"],
  ["Andante from Piano Concerto No. 2", "Dmitri Shostakovich"],
  ["Andante from Water Music", "George Frideric Handel"],
  ["Andante No. 7", "Joseph Haydn"],
  ["Aria from Griselda", "Antonio Vivaldi"],
  ["Arioso", "J. S. Bach"],
  ["Ashokan Farewell", "Jay Ungar"],
  ["Ave Maria", "Bach / Gounod"],
  ["Ave Maria", "Franz Schubert"],
  ["Ave Verum Corpus", "W. A. Mozart"],
  ["Badinerie", "J. S. Bach"],
  ["Bist du bei mir", "J. S. Bach"],
  ["Bourrée", "George Frideric Handel"],
  ["Brandenburg Concerto No. 1 — Selections", "J. S. Bach"],
  ["Brandenburg Concerto No. 2 — Selections", "J. S. Bach"],
  ["Brandenburg Concerto No. 3 — Selections", "J. S. Bach"],
  ["Brandenburg Concerto No. 4 — Selections", "J. S. Bach"],
  ["Brandenburg Concerto No. 5 — Selections", "J. S. Bach"],
  ["Bridal Chorus from Lohengrin", "Richard Wagner"],
  ["Canon in D", "Johann Pachelbel"],
  ["Choral", "Robert Schumann"],
  ["Courante", "George Frideric Handel"],
  ["Entrance of the Queen of Sheba", "George Frideric Handel"],
  ["Festival March", "Felix Mendelssohn"],
  ["Finlandia Hymn", "Jean Sibelius"],
  ["For All the Saints (Sine Nomine)", "Ralph Vaughan Williams"],
  ["Gavotte", "William Boyce"],
  ["Gavotte", "François-Joseph Gossec"],
  ["Gavotte", "Sergei Prokofiev"],
  ["Gavotte from Il pastor fido", "George Frideric Handel"],
  ["Gavotte from Orestes", "George Frideric Handel"],
  ["Gigue from Partenope", "George Frideric Handel"],
  ["Gigue from Suite No. 3 in D Major", "J. S. Bach"],
  ["Greensleeves", "Traditional English"],
  ["Gymnopédies Nos. 1, 2 & 3", "Erik Satie"],
  ["String Quartet Selections", "Joseph Haydn"],
  ["The Heavens Declare the Glory of God", "Benedetto Marcello"],
  ["Hornpipe", "George Frideric Handel"],
  ["If With All Your Hearts", "Felix Mendelssohn"],
  ["Intermezzo", "Pietro Mascagni"],
  ["Jesu, Joy of Man's Desiring", "J. S. Bach"],
  ["Jig from Oreste", "George Frideric Handel"],
  ["Joyful, Joyful, We Adore Thee", "Ludwig van Beethoven"],
  ["La Réjouissance", "George Frideric Handel"],
  ["Larghetto from Theodora", "George Frideric Handel"],
  ["Largo from Xerxes", "George Frideric Handel"],
  ["March", "George Frideric Handel"],
  ["March from The Marriage of Figaro", "W. A. Mozart"],
  ["March from Rinaldo", "George Frideric Handel"],
  ["March in D from Tigrane", "Alessandro Scarlatti"],
  ["March in D", "George Frideric Handel"],
  ["March in D Major", "J. S. Bach"],
  ["Méditation from Thaïs", "Jules Massenet"],
  ["Meditation from Motet", "J. S. Bach"],
  ["Menuet from Arminio", "George Frideric Handel"],
  ["Menuet from Eine kleine Nachtmusik", "W. A. Mozart"],
  ["Menuet from Il pastor fido", "George Frideric Handel"],
  ["Menuet from Imeneo", "George Frideric Handel"],
  ["Menuet from Orfeo ed Euridice", "Christoph Willibald Gluck"],
  ["Menuet in G", "Ludwig van Beethoven"],
  ["Minuetto from String Quintet in E Major", "Luigi Boccherini"],
  ["My Heart Ever Faithful", "J. S. Bach"],
  ["O Perfect Love", "Joseph Barnby"],
  ["Panis Angelicus", "César Franck"],
  ["Pavane", "Maurice Ravel"],
  ["Prelude to Te Deum", "Marc-Antoine Charpentier"],
  ["Presto from Sonatina in F", "Georg Philipp Telemann"],
  ["Rigaudon", "André Campra"],
  ["Rigaudon from Suite No. 5", "Henry Purcell"],
  ["Romanza from Eine kleine Nachtmusik", "W. A. Mozart"],
  ["Rondeau", "J. S. Bach"],
  ["Rondeau", "Jean-Joseph Mouret"],
  ["Rondeau from Ariodante", "George Frideric Handel"],
  ["Rondeau from Symphonies de Fanfares", "Jean-Joseph Mouret"],
  ["Rondo Alla Turca", "W. A. Mozart"],
  ["Rondo from Incidental Music", "Henry Purcell"],
  ["Salut d'Amour", "Edward Elgar"],
  ["Scheherazade Theme", "Nikolai Rimsky-Korsakov"],
  ["Music for the Royal Fireworks — Selections", "George Frideric Handel"],
  ["Water Music — Selections", "George Frideric Handel"],
  ["Serenade — Andante Cantabile", "Joseph Haydn"],
  ["Sheep May Safely Graze", "J. S. Bach"],
  ["Sicilienne from Variations on a Theme by Haydn", "Johannes Brahms"],
  ["Simple Gifts", "Shaker Melody"],
  ["Sinfonia from Giustino", "George Frideric Handel"],
  ["Sinfonia from Scipione", "George Frideric Handel"],
  ["Sinfonia from Xerxes", "George Frideric Handel"],
  ["Sleeping Beauty Waltz", "Pyotr Ilyich Tchaikovsky"],
  ["Sonata in F", "George Frideric Handel"],
  ["Song Without Words", "Felix Mendelssohn"],
  ["Spring — Largo", "Antonio Vivaldi"],
  ["St. Anthony Chorale", "Johannes Brahms"],
  ["Suite from The Fairy Queen", "Henry Purcell"],
  ["Suite in D Major", "J. S. Bach"],
  ["Tambourin", "François-Joseph Gossec"],
  ["The Four Seasons — Excerpts", "Antonio Vivaldi"],
  ["The Lord's Prayer", "Albert Hay Malotte"],
  ["Theme from The Magic Flute", "W. A. Mozart"],
  ["Theme from Symphony No. 4", "Franz Schubert"],
  ["Theme from Gloria", "Antonio Vivaldi"],
  ["Three Slavonic Dances", "Antonín Dvořák"],
  ["Träumerei", "Robert Schumann"],
  ["Trumpet Tune", "Henry Purcell"],
  ["Trumpet Voluntary", "Jeremiah Clarke"],
  ["Prince of Denmark's March", "Jeremiah Clarke"],
  ["Two Sonatas for Two Violins and Cello", "Giuseppe Tartini"],
  ["Vivace from Sonata in F Major", "Georg Philipp Telemann"],
  ["Wachet auf", "J. S. Bach"],
  ["Water Music Suite", "George Frideric Handel"],
  ["Wedding March", "Felix Mendelssohn"],
  ["When I Am Laid in Earth", "Henry Purcell"],
  ["Winter", "Antonio Vivaldi"],
];

const pop: [string, string][] = [
  ["A Thousand Years", "Christina Perri"],
  ["A Time for Us", "Nino Rota"],
  ["All I Ask of You", "Andrew Lloyd Webber"],
  ["All You Need Is Love", "The Beatles"],
  ["Any Way You Want It", "Journey"],
  ["Ashokan Farewell", "Jay Ungar"],
  ["At Last", "Etta James"],
  ["Beautiful Day", "U2"],
  ["Bitter Sweet Symphony", "The Verve"],
  ["Can't Help Falling in Love", "Elvis Presley"],
  ["Chasing Cars", "Snow Patrol"],
  ["Don't Stop Believin'", "Journey"],
  ["Every Little Thing She Does Is Magic", "The Police"],
  ["Fields of Gold", "Sting"],
  ["Firework", "Katy Perry"],
  ["A Groovy Kind of Love", "Phil Collins"],
  ["Grow Old with Me", "John Lennon"],
  ["Hallelujah", "Leonard Cohen"],
  ["Happy Together", "The Turtles"],
  ["Here Comes the Sun", "The Beatles"],
  ["Hey, Soul Sister", "Train"],
  ["How Beautiful", "Twila Paris"],
  ["How Sweet It Is", "James Taylor"],
  ["I Will Be Here", "Steven Curtis Chapman"],
  ["I'm Yours", "Jason Mraz"],
  ["In My Life", "The Beatles"],
  ["Just the Way You Are", "Bruno Mars"],
  ["Love Story", "Taylor Swift"],
  ["Marching Bands of Manhattan", "Death Cab for Cutie"],
  ["The Marriage of Figaro", "W. A. Mozart"],
  ["Marry Me", "Train"],
  ["Marry You", "Bruno Mars"],
  ["Memory from Cats", "Andrew Lloyd Webber"],
  ["Moon River", "Henry Mancini"],
  ["Oh, Pretty Woman", "Roy Orbison"],
  ["One Hand, One Heart", "Leonard Bernstein"],
  ["Only Time", "Enya"],
  ["Paradise", "Coldplay"],
  ["Parent's Prayer", "Steven Curtis Chapman"],
  ["Purple Haze", "Jimi Hendrix"],
  ["Somewhere Out There", "James Horner"],
  ["Stay with Me", "Sam Smith"],
  ["Summertime from Porgy and Bess", "George Gershwin"],
  ["Surely the Presence", "Lanny Wolfe"],
  ["Sweet Child o' Mine", "Guns N' Roses"],
  ["Take My Breath Away", "Berlin"],
  ["The Ludlows from Legends of the Fall", "James Horner"],
  ["The Rose", "Amanda McBroom"],
  ["Unchained Melody", "The Righteous Brothers"],
  ["Viva la Vida", "Coldplay"],
  ["Wedding Song (There Is Love)", "Paul Stookey"],
  ["When a Man Loves a Woman", "Percy Sledge"],
  ["When You Say Nothing at All", "Alison Krauss"],
  ["Wonderwall", "Oasis"],
  ["Wouldn't It Be Nice", "The Beach Boys"],
  ["Yellow", "Coldplay"],
  ["You and Me", "Lifehouse"],
  ["You Raise Me Up", "Josh Groban"],
  ["Your Song", "Elton John"],
];

const entrance: [string, string][] = [
  ["Bridal Chorus (Here Comes the Bride)", "Richard Wagner"],
  ["Trumpet Voluntary", "Jeremiah Clarke"],
  ["Prelude to Te Deum", "Marc-Antoine Charpentier"],
  ["Canon in D", "Johann Pachelbel"],
  ["Rondeau", "Jean-Joseph Mouret"],
];

const recessional: [string, string][] = [
  ["Wedding March", "Felix Mendelssohn"],
  ["La Réjouissance", "George Frideric Handel"],
  ["Entrance of the Queen of Sheba", "George Frideric Handel"],
  ["Rondeau", "Jean-Joseph Mouret"],
  ["Ode to Joy", "Ludwig van Beethoven"],
  ["Hornpipe in D", "George Frideric Handel"],
];

const groups: [Category, [string, string][]][] = [
  ["Classical", classical],
  ["Pop", pop],
  ["Entrance", entrance],
  ["Recessional", recessional],
];

export const songs: Song[] = groups.flatMap(([category, entries]) =>
  entries.map(([title, composer], index) => ({
    id: `${category.toLowerCase()}-${index}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    title,
    composer: composer || "Composer not listed",
    category,
  })),
);
